CREATE TABLE IF NOT EXISTS projects(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''), 
  priority integer NOT NULL,
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''), 
  done boolean,
  projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects ( name, priority, description, deliverydate) 
VALUES('Make a webApp', 1, 'Using Js', '2022-05-12');

INSERT INTO projects ( name, priority, description, deliverydate) 
VALUES('Make an App ', 2, 'Using C++', '2022-05-05');

-- Insert task data

INSERT INTO tasks (name,done,projectId) VALUES
('dowload Vue js',false, 1);

INSERT INTO tasks (name,done,projectId) VALUES
('create ui web',false, 1);

INSERT INTO tasks (name,done,projectId) VALUES
('dowload flutter',false, 2);

INSERT INTO tasks (name,done,projectId) VALUES
('Desing UI',false, 2);